export default {
  TOGGLE_HIDDEN : 'TOGGLE_HIDDEN',
  ADD_ACTIVITY : 'ADD_ACTIVITY',
  REMOVE_ACTIVITY : 'REMOVE_ACTIVITY',
  ADD_FAV : 'ADD_FAV',
  REMOVE_FAV : 'REMOVE_FAV',
  UPDATE_BUDGET : 'UPDATE_BUDGET',
  SHOW_ACTIVITIES: 'SHOW_ACTIVITIES',
  SHOW_FAVS: 'SHOW_FAVS',
}